repos:
  # autoflakeは未使用のインポートと変数を削除し、コードをクリーンアップする。
  # 特定のファイルでautoflakeを無視するには、SKIP=autoflake pre-commit run --all-files を使用する。
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variables']
        language_version: python3.9

  # isortはインポート文を整理し、フォーマットする。
  # 特定のファイルでisortを無視するには、SKIP=isort pre-commit run --all-files を使用する。
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        language_version: python3.9
        additional_dependencies: ["toml"]

  # blackはコードをPEP 8スタイルに自動フォーマットする。
  # 特定のファイルでblackを無視するには、SKIP=black pre-commit run --all-files を使用する。
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9

  # flake8はスタイル違反やプログラミングエラーを検出するリンター。
  # 特定の行でflake8を無視するには、その行の末尾に # noqa を追加する。
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]
        language_version: python3.9

  # mypyは型注釈を用いた静的型チェックを行う。
  # 特定の行でmypyを無視するには、その行の末尾に # type: ignore を追加する。
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        language_version: python3.9
